### PR TITLE
initial css grid

### PR DESCRIPTION
**Pull request by dwido**
This is just the structure of the css grid and grid component

image

### CODE REVIEW

**Comment by dwido** [comment]
✔️ Deploy Preview for *stupefied-hodgkin-46481a* ready!


🔨 Explore the source changes: 3d66e226dc4dba2e115b7e3f1d3bbcaa732826b7

🔍 Inspect the deploy log: [https://app.netlify.com/sites/stupefied-hodgkin-46481a/deploys/62062f402b5c100008cf6253](https://app.netlify.com/sites/stupefied-hodgkin-46481a/deploys/62062f402b5c100008cf6253)

😎 Browse the preview: [https://deploy-preview-2--stupefied-hodgkin-46481a.netlify.app](https://deploy-preview-2--stupefied-hodgkin-46481a.netlify.app)

**Comment by yossefdiy** [comment]
ok

**Review by yossefdiy — APPROVED** [review]

**Comment by yossefdiy** [comment]
ok

**Review by yossefdiy — APPROVED** [review]

**Comment by yossefdiy** [comment]
ok

**Review by yossefdiy — APPROVED** [review]

**Comment by yossefdiy** [comment]
ok

**Pull request merged**
